default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.darksky_weather_data
    - group.environment_data
    - camera.bos
    - camera.yankee_magazine
    - camera.yankee_magazine_backyard
    - group.locator
    - group.transmission
    - group.guestroom
    - group.bedroom
    - group.kitchen
    - group.diningroom
    - group.bitcoin
    - group.pihole
    - group.all_automations
    - group.candlelight
