- platform: mqtt
  name: Mudroom Temperature
  state_topic: homeassistant/mudroom/temp
  qos: 0
  unit_of_measurement: "째F" 

- platform: mqtt
  name: Bedroom Temperature
  state_topic: homeassistant/bedroom/temp
  qos: 0
  unit_of_measurement: "째F" 

- platform: mqtt
  name: Bedroom Humidity
  state_topic: homeassistant/bedroom/hum
  qos: 0
  unit_of_measurement: "%"

- platform: mqtt
  name: Livingroom Temperature
  state_topic: homeassistant/livingroom/temp
  qos: 0
  unit_of_measurement: "째F" 

- platform: mqtt
  name: Livingroom Humidity
  state_topic: homeassistant/livingroom/hum
  qos: 0
  unit_of_measurement: "%"

- platform: template
  sensors:
    darksky_temp:
      unit_of_measurement: "째F" 
      value_template: "{{ states.weather.dark_sky.attributes.temperature }}"
    darksky_hum:
      unit_of_measurement: "%"
      value_template: "{{ states.weather.dark_sky.attributes.humidity }}"
    darksky_pressure:
      unit_of_measurement: "mb"
      value_template: "{{ states.weather.dark_sky.attributes.pressure }}"
    darksky_wind:
      unit_of_measurement: "mph"
      value_template: "{{ states.weather.dark_sky.attributes.wind_speed }}"
    darksky_hourly_forecast:
      value_template: "{{ states.weather.dark_sky.attributes.hourly_forecast_summary }}"
    darksky_daily_forecast:
      value_template: "{{ states.weather.dark_sky.attributes.daily_forecast_summary }}"

# The following has been deprecated...
# - platform: template
#   sensors:
#     furnace_attribute_mode:
#       friendly_name: "Furnance mode"
#       entity_id: climate.dublin
#       value_template: "{{ states.climate.dublin.attributes.operation_mode }}"
#     furnace_attribute_operation:
#       friendly_name: "Furnance operation"
#       entity_id: climate.dublin
#       value_template: "{{ states.climate.dublin.attributes.operation }}"
#     furnace_attribute_fan:
#       friendly_name: "Furnance fan"
#       entity_id: climate.dublin
#       value_template: "{{ states.climate.dublin.attributes.fan }}"
#     furnace_attribute_vacation:
#       friendly_name: "Furnance Vacation Mode"
#       entity_id: climate.dublin
#       value_template: "{{ states.climate.dublin.attributes.away_mode }}"

